[package]
name = "cf-license-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
spdx = "0.10.7"
tokio = "1.41.1"
zstd = "0.13.2"
