[project]
authors = ["PaulKMueller <paul.mueller@quantco.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "cf-license-stats"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
stream = "streamlit run app.py"

[dependencies]
plotly = ">=6.0.1,<7"
streamlit = ">=1.44.1,<2"
pandas = ">=2.2.3,<3"
